[meta]
  title = "Prerecorded Node.js Starter"
  description = "Basic demo for using Deepgram to transcribe files with Node.js"
  author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
  useCase = "Prerecorded"
  language = "JavaScript"
  framework = "Node"

[build]
  command = "npm install"

[config]
  sample = "config.json.example"
  output = "config.json"

[post-build]
  message = "Run `npm start` to get up and running."
